FROM ros:jazzy-ros-base

SHELL ["/bin/bash", "-c"]

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-colcon-common-extensions \
    python3-pip \
    python3-pytest \
    python3-yaml \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /ws
COPY . /ws/src/MultiRobotBattle

RUN source /opt/ros/jazzy/setup.bash && colcon build --symlink-install
