#!/usr/bin/env python3
"""Benchmark comparison tables: planners/controllers and MAPF solvers, side by side.

Runs every navigation policy on every bundled scenario, and every MAPF solver on
the MovingAI example, then writes a Markdown report with two comparison tables to
``benchmarks/comparison.md`` (and prints it). Everything is pure and
deterministic, so the report is reproducible — regenerate it after a change and
diff it, or read the checked-in copy.

    python3 scripts/compare_planners.py            # write + print the report
    python3 scripts/compare_planners.py --check     # fail if the report is stale

The numbers are produced by the same ``mrn_sim.benchmark`` / MovingAI machinery
the CI regression gate (``scripts/benchmark_gate.py``) checks, so a row here that
changes is a row the gate guards.
"""

from __future__ import annotations

import argparse
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_REPO = os.path.abspath(os.path.join(_HERE, os.pardir))
sys.path.insert(0, os.path.join(_REPO, "mrn_sim"))
sys.path.insert(0, os.path.join(_REPO, "mrn_coord"))

_REPORT = os.path.join(_REPO, "benchmarks", "comparison.md")
_SCENARIOS = ["around_obstacle", "crossing", "doorway"]

# label -> how to build the policy from a scenario
_POLICIES = [
    ("grid A* + pursuit", "navigate"),
    ("Hybrid A* (kinodynamic)", "kinodynamic"),
    ("grid A* + DWA", "dwa"),
    ("Hybrid A* + DWA", "dwa_kino"),
    ("grid A* + ORCA", "orca"),
]


def _build(policy: str):
    from mrn_sim.benchmark import (
        dwa_policy,
        kinodynamic_policy,
        navigate_policy,
        orca_policy,
    )
    return {
        "navigate": navigate_policy,
        "kinodynamic": kinodynamic_policy,
        "dwa": dwa_policy,
        "dwa_kino": lambda s: dwa_policy(s, planner="kino"),
        "orca": orca_policy,
    }[policy]


def _nav_rows():
    from mrn_sim.benchmark import load_scenario, run_scenario

    rows = []
    for sname in _SCENARIOS:
        scenario = load_scenario(
            os.path.join(_REPO, "mrn_sim", "scenarios", sname + ".yaml"))
        for label, policy in _POLICIES:
            r = run_scenario(scenario, _build(policy)(scenario),
                             dt=0.1, max_steps=600)
            rows.append((sname, label, r))
    return rows


def _mapf_rows():
    from mrn_coord.mapf.movingai import load_map, load_scen, run_mapf_benchmark

    bench = os.path.join(_REPO, "mrn_coord", "benchmarks")
    grid = load_map(os.path.join(bench, "example.map"))
    tasks = load_scen(os.path.join(bench, "example.scen"))
    rows = []
    for solver in ("cbs", "prioritized"):
        res = run_mapf_benchmark(grid, tasks, solver=solver, max_expansions=50_000)
        rows.append((solver, res))
    return rows


def _fmt(report_lines):
    return "\n".join(report_lines) + "\n"


def build_report() -> str:
    lines = [
        "# Benchmark comparison",
        "",
        "Generated by `scripts/compare_planners.py` (pure + deterministic; "
        "regenerate after changes). The same metrics are regression-gated by "
        "`scripts/benchmark_gate.py`.",
        "",
        "## Navigation policies",
        "",
        "Each navigation policy run on every bundled scenario "
        "(`mrn_sim/scenarios/`). `success` = all goals reached; `makespan` = "
        "time to the last arrival; `clear` = min obstacle-surface clearance (m); "
        "`min dist` = min inter-robot centre distance (m); `coll` = colliding "
        "steps.",
        "",
        "| scenario | policy | success | steps | makespan (s) | path len (m) | "
        "clear (m) | min dist (m) | coll |",
        "| --- | --- | :-: | --: | --: | --: | --: | --: | :-: |",
    ]
    for sname, label, r in _nav_rows():
        d = r.as_dict()
        min_dist = "—" if r.goals_total < 2 else f"{d['min_robot_distance']:.2f}"
        lines.append(
            f"| {sname} | {label} | {'✓' if d['success'] else '✗'} | "
            f"{d['steps']} | {d['makespan_sec']:.1f} | "
            f"{d['total_path_length']:.1f} | {d['min_obstacle_clearance']:.2f} | "
            f"{min_dist} | {d['collisions']} |"
        )

    lines += [
        "",
        "**Reading it.** Grid A\\* plans fast but axis-aligned; the kinodynamic "
        "Hybrid A\\* trades a little planning time for smooth, bounded-curvature "
        "paths (often fewer steps and more clearance to follow). DWA decides "
        "speed and avoidance by forward-simulating accel-limited velocities, so "
        "it tracks tighter and reacts to the other robots as moving obstacles, "
        "at a higher per-tick compute cost.",
        "",
        "## MAPF solvers (MovingAI example)",
        "",
        "Conflict-Based Search (optimal sum-of-costs) vs. prioritized planning "
        "(fast, incomplete) on `mrn_coord/benchmarks/example.{map,scen}`.",
        "",
        "| solver | solved | makespan | sum of costs |",
        "| --- | :-: | --: | --: |",
    ]
    for solver, res in _mapf_rows():
        solved = res.get("solved", False)
        mk = res.get("makespan", "—")
        soc = res.get("sum_of_costs", "—")
        lines.append(
            f"| {solver} | {'✓' if solved else '✗'} | {mk} | {soc} |")
    lines.append("")
    return _fmt(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="fail if the checked-in report is stale")
    args = parser.parse_args()

    report = build_report()
    if args.check:
        if not os.path.exists(_REPORT):
            print(f"FAIL: {_REPORT} does not exist; run compare_planners.py")
            return 1
        with open(_REPORT, "r", encoding="utf-8") as fh:
            current = fh.read()
        if current != report:
            print(f"FAIL: {_REPORT} is stale; rerun scripts/compare_planners.py")
            return 1
        print(f"ok: {_REPORT} is up to date")
        return 0

    os.makedirs(os.path.dirname(_REPORT), exist_ok=True)
    with open(_REPORT, "w", encoding="utf-8") as fh:
        fh.write(report)
    print(report)
    print(f"wrote {_REPORT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
